### ISSUE TITLE
dcp_inspect: DC Naming Convention out of date

### ISSUE THREAD

**Issue by kevinlondon** [wolfgangw/digital_cinema_tools_distribution#20]
The latest version on digitalcinemanamingconvention.com is v9 and, from looking at the code, the current version is 3.9. There's been a few changes, which only really affect the hints provided.

3.9: https://web.archive.org/web/20110710124916/http://digitalcinemanamingconvention.com/

9.0: www.digitalcinemanamingconvention.com

Changes that I saw:
- Naming changed from ALL-CAPS to InitialCaps
- More approved Content Types
- Addition of Content Type Modifiers
- Addition of optional aspect ratio number after letter
- Removed framerate from resolution
- Include Standard type (IOP, SMPTE)

**Comment by wolfgangw** [comment]
Considered fixed by removing the feature (https://github.com/wolfgangw/backports/commit/117a70bb9c388a2af2551e57a2d0b22271d815a9).

Seriously, though: In order to make sense in the modern day and age, naming will have to be cross checked with

1. composition metadata
2. asset metadata fields
3. actual asset properties

(2) was done in previous versions. But (1) is not yet read in any useful way. Worst case: all 4 data contexts differ.

Good to see that composition metadata is adopted in the field. Once it is in authoring systems they will likely also generate naming from that and, thus, automatically align with ISDCF's naming convention. `dcp_inspect` would still have to check.
